[build]
  command = "npx eleventy"
  publish = "_site"

[dev]
  command = "npx eleventy --serve"
  port = 3999
  publish = "_site"


[functions]
node_bundler = "esbuild"
external_node_modules = []


[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200


# Security + allow Razorpay/AdSense
[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "strict-origin-when-cross-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
Content-Security-Policy = "default-src 'self'; connect-src 'self' https:; img-src 'self' https: data:; script-src 'self' 'unsafe-inline' https://checkout.razorpay.com https://pagead2.googlesyndication.com; style-src 'self' 'unsafe-inline' https:; frame-src https://checkout.razorpay.com https://*.google.com https://*.googlesyndication.com;"
